### ISSUE TITLE
Extend the functionality to add more features to Zimbra Contacts crowdfunder?

### ISSUE THREAD

**Issue by ghost** [Zimbra-Community/io_nomennesc_extracontact#1]
Right now this Zimlet adds only 1 custom field to the address book contacts, however it could be made in a way to allow an Admin to set a set of fields to add, or have the user configure their own.

Since it does not require back-end changes, this opens the door to fix:

https://bugzilla.zimbra.com/show_bug.cgi?id=41745
https://bugzilla.zimbra.com/show_bug.cgi?id=57287

A crowd fund possibility IMHO.

**Comment by ghost** [comment]
Maybe implement the vcf standard

**Comment by nomennesc-io** [comment]
Multiple custom fields can now be defined in the config_template.xml (only tested with plain text input fields)
